version: "3"

services:
  # The application
  lwhh-app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./src:/opt/app/src
    environment:
      - PORT=3000
      - DATABASE=postgres://postgres:8821025@lwhh-postgres:5432/lwhh
    depends_on:
      - lwhh-postgres
  # Database Server
  lwhh-postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_PASSWORD=8821025
      - POSTGRES_DB=lwhh  
    logging:
      driver: none

    